# Generated by Django 4.1.2 on 2022-11-02 18:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('appUno', '0002_apunte'),
    ]

    operations = [
        migrations.AddField(
            model_name='apunte',
            name='cedula',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='appUno.contacto'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='contacto',
            name='cedula',
            field=models.CharField(max_length=10),
        ),
    ]
